#!/usr/bin/env sh

# show dotfiles
defaults write com.apple.finder AppleShowAllFiles TRUE

# Show hidden files
defaults write com.apple.Finder AppleShowAllFiles -bool true

# show file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# avoid .DS_Store files
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# brew bundle install
~/dotfiles/scripts/bbiv

